#Service MYSQL
apiVersion: v1
kind: Service
metadata: 
  name: drupal-mysql-service
spec: 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

    
  selector: 
    app: drupal-mysql

#Service Drupal
--- 
apiVersion: v1
kind: Service
metadata: 
  name: drupal-service
spec: 
  ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: drupal-app
  type: LoadBalancer
